# Generated by Django 3.2.4 on 2021-07-01 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QandAmodel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-created_at'], 'verbose_name': 'Answer', 'verbose_name_plural': 'Answers'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created_at', '-updated_at']},
        ),
    ]
