# Generated by Django 3.2.4 on 2021-07-03 20:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('QandAmodel', '0003_question_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='upvotes',
            field=models.ManyToManyField(related_name='answers_upvotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
