# Generated by Django 3.2.4 on 2021-07-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QandAmodel', '0004_answer_upvotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='slug',
            field=models.SlugField(default='slug', max_length=250, unique_for_date='published'),
        ),
    ]
