# Generated by Django 3.2.4 on 2021-07-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20210708_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(default='creer', max_length=255, null=True),
        ),
    ]
